//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infrastructure_inquiry.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("infrastructure_inquiry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;List&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;İl seçiniz&quot;,
        ///      &quot;latitude&quot;: &quot;&quot;,
        ///      &quot;longitude&quot;: &quot;&quot;,
        ///      &quot;population&quot;: 0,
        ///      &quot;region&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;name&quot;: &quot;Adana&quot;,
        ///      &quot;latitude&quot;: &quot;37.0000&quot;,
        ///      &quot;longitude&quot;: &quot;35.3213&quot;,
        ///      &quot;population&quot;: 2183167,
        ///      &quot;region&quot;: &quot;Akdeniz&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 2,
        ///      &quot;name&quot;: &quot;Adıyaman&quot;,
        ///      &quot;latitude&quot;: &quot;37.7648&quot;,
        ///      &quot;longitude&quot;: &quot;38.2786&quot;,
        ///      &quot;population&quot;: 602774,
        ///      &quot;region&quot;: &quot;Güneydoğu Anadolu&quot;
        ///    },
        ///    {
        ///      &quot; [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cities_of_turkey {
            get {
                return ResourceManager.GetString("cities_of_turkey", resourceCulture);
            }
        }
    }
}
